import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/NavBar";
import SideBar from "@/Components/SideBar";
import TopNavBar from "@/Components/TopNavBar";
import { SearchProvider } from "@/context/SearchContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SearchProvider>
        <div className="flex flex-col min-h-screen sm:flex-row">
          <SideBar />
          <div className="flex-1 relative sm:bg-[#f4f4f5]">
            <TopNavBar />
            <div className="sm:mt-24 sm:mx-4 md:mx-8 sm:py-4 bg-white rounded-2xl h-[90vh] sm:h-[83vh] flex flex-col">
              <NavBar />
              <div className="flex-1 overflow-hidden">
                {children}
              </div>
            </div>
          </div>
        </div>
        </SearchProvider>
      </body>
      
    </html>
  );
}